version: "3"
services:
  mywebapp:
    build:
      context: .
      dockerfile: Dockerfile

    volumes:
    - ./src/:/var/www/html

    environment:
      - XDEBUG_CONFIG=remote_host=host.docker.internal

    ports:
        - "80:80"
    links:
      - db:db
    restart: always

  db:
    image: mysql
    volumes:
      - /mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root

  myadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    links:
      - db:db
